version: '3'

services:
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'pA_sw0rd'

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - 3030:3000
